language: go
go:
  - "1.10"
services:
  - docker

install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v

env:
  global:
    - TEZOS_RPC_PORT=18731

before_script: |
  # Start tezos sandbox node
  (cd test ; docker-compose up --build) &
  # Wait for network to start
  sleep 5
  until $(curl --output /dev/null --silent --fail http://127.0.0.1:$TEZOS_RPC_PORT/monitor/bootstrapped); do
    printf '.'
    sleep 5
  done

script:
  - go test -race -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false 
