language: go
go:
  - "1.10"
services:
  - docker

install:
  - wget https://gitlab.com/tezos/tezos/raw/master/scripts/alphanet.sh
  - chmod +x alphanet.sh
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v

before_script: |
  # Start alphanet
  ./alphanet.sh start --rpc-port 8732 --no-bootstrap-peers --sandbox
  # Wait for network to start
  until $(curl --output /dev/null --silent --fail http://127.0.0.1:8732/monitor/bootstrapped); do
      printf '.'
      sleep 5
  done

script:
  - go test -race -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false 
